### ISSUE TITLE
[BUG] Navigation Opener does not render well on small screens

### ISSUE THREAD

**Issue by Peartes** [BuildForSDG/Team-097#12]
**Bug**
When you resize the navbar, the navopener does not render well

**To Reproduce**
Resize the browser

**Expected behaviour**
The NavOpener should not be there anymore. Remove or adjust the navbar layout

**Additional context**
The NavBar uses grid layout to divide the screen between the logo and banner, I am guessing it doesn't work well with bootstrp
Just remove the navopener, it is no more needed since all those links are now in dashboard

**Comment by doktaslim** [comment]
This issue has been fixed and a PR sent.

**Comment by Peartes** [comment]
I just pulled the fix, it didn't fix it. I am re-opening the issue. Also chi, you didn't raise a pull request. You pushed directly.

**Comment by doktaslim** [comment]
I already fixed the issue. Send a screenshot of what it looks like on your machine.
